### ISSUE TITLE
(todo) --dither + --autocontrast breaking

### ISSUE THREAD

**Issue by TheFel0x** [TheFel0x/img2braille#1]
results in blank image
i should fix this

**Comment by wh1rstclass** [comment]
Not every picture.
I have tried with B&W arts, some of them have been done correctly
If needed, i can send a zip, for debugging

**Comment by TheFel0x** [comment]
> Not every picture. I have tried with B&W arts, some of them have been done correctly If needed, i can send a zip, for debugging

That would be very nice!

**Comment by wh1rstclass** [comment]
[ahegao.zip](https://github.com/TheFel0x/img2braille/files/7914889/ahegao.zip)
Some of pic output blank, some -- not

**Comment by TheFel0x** [comment]
Seems like it's working fine now. Thank you for the test images!
